mwDev/mwDev/src/objects/mwJob__c.object
<CustomObject>
    <description>Object to hold Job for an Opportunity</description>
    <fields>
        <fullName>mwJobNo__c</fullName>
        <externalId>true</externalId>
        <label>Job No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>mwOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>mwJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>mw-{DD}-{MM}-{YY}-{00000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mwDev/mwDev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Quotation_No__c</fullName>
        <externalId>true</externalId>
        <label>Quotation No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

mwDev/mwDev/src/classes/mwUpdateOppIdTriggerTest.cls
@IsTest global with sharing class mwUpdateOppIdTriggerTest
{
    static Opportunity opp;
   
    private static void init()
    {
        Account acc = new Account(name = 'testAcc01');
        insert acc;
        
        opp = new Opportunity(name = 'opp001' , Quotation_No__c = '1000', StageName = 'Prospecting' , CloseDate = system.TODAY(), 
        ForecastCategoryName = 'Pipeline', Account = acc);        
            
        insert opp;
    }
    
    public static testMethod void testOppId()
    {
        init();

        mwJob__c job = new mwJob__c(name = 'job001' , mwJobNo__c = '1000-4');
        insert job;   
        
        mwJob__c job_new = [select id, mwOpportunity__c from mwJob__c where name = :job.name limit 1];
        System.assertEquals(job_new.mwOpportunity__c,opp.id);
        
    }
    
    public static testMethod void testNoOppId()
    {
        init();

        mwJob__c job = new mwJob__c(name = 'job002' , mwJobNo__c = '10002-4');
        insert job;   
        
        mwJob__c job_new = [select id, mwOpportunity__c from mwJob__c where name = :job.name limit 1];
        System.assertEquals(job_new.mwOpportunity__c,null);
        
    }
        
}